name: Run SQL File

on: [push]

jobs:
  run_sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Run SQL script
      run: |
        sqlcmd -S servername -d database_name -U username -P password -i ${{ github.workspace }}/SCRIPTDATAuma.sql
