name: Run SQL Script

on: [push]

jobs:
  run_sql_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SQL Server tools
      uses: actions/setup-msbuild

    - name: Run SQL script
      run: |
        sqlcmd -S LAPTOP-UBHBRE86\MSSQLSERVER02 -d UMA -U LAPTOP-UBHBRE86\kunal -i SCRIPTDATAuma.sql
